### ISSUE TITLE
DecimalField results in JSON serialization error

### ISSUE THREAD

**Issue by jorenham** [wagtail/wagtail-condensedinlinepanel#30]
I have a model that is used in a `CondensedInlinePanel` which uses a `DecimalField` and I get the following traceback:

```pytb
Traceback (most recent call last):
  File "/project/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/project/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/project/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/project/lib/python3.5/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/project/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py", line 31, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/project/lib/python3.5/site-packages/wagtail/wagtailadmin/views/pages.py", line 481, in edit
    edit_handler = edit_handler_class(instance=page, form=form)
  File "/project/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 269, in __init__
    self.children.append(child(instance=self.instance, form=self.form))
  File "/project/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 269, in __init__
    self.children.append(child(instance=self.instance, form=self.form))
  File "/project/lib/python3.5/site-packages/condensedinlinepanel/edit_handlers.py", line 145, in __init__
    self.formset.to_json()
  File "/project/lib/python3.5/site-packages/condensedinlinepanel/edit_handlers.py", line 132, in to_json
    for field_name in self.empty_form.fields.keys()
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Decimal('2250.00') is not JSON serializable
```

Suggestions?

**Comment by kaedroho** [comment]
This appears to have been solved by #36
