### ISSUE TITLE
Update for Wagtail 2.0

### ISSUE THREAD

**Issue by SalahAdDin** [wagtail/wagtail-condensedinlinepanel#32]
I'm testing the next version and i tried to update this package, but i have a problem with `edit_handlers`: https://github.com/wagtail/wagtail/commit/5fc191b116ee835762c282e13a5829fa873cc516#diff-507d1915f772f388fd0ef0447953585f in this commit `BaseInlinePanel` was removed, so we have to replace it with the normal `InlinePanel`; but i get a problem with it:
```
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/wagtail/admin/checks.py", line 63, in get_form_class_check
    if not issubclass(edit_handler.get_form_class(), WagtailAdminPageForm):
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 336, in get_form_class
    fields=self.required_fields(),
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 261, in required_fields
    fields.extend(handler.required_fields())
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 261, in required_fields
    fields.extend(handler.required_fields())
TypeError: required_fields() missing 1 required positional argument: 'self'
```

What's happening here?

**Comment by kaedroho** [comment]
Hmm.. what's probably happening is that ``handler`` variable is a class when it should be an instance. Double check your panels configuration on your model.

**Comment by SalahAdDin** [comment]
@kaedroho I changed `BaseInlinePanel` by `InlinePanel` and after i got this problem.

**Comment by kaedroho** [comment]
Ahh, I noticed that and changed it back before I merged your branch.
